services:
  - type: web
    name: pigeon-font-maker
    runtime: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y potrace fontforge
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0